# Generated by Django 5.1.3 on 2026-09-11 02:49

import django.db.models.deletion
from django.db import migrations, models


def copy_members_to_table(apps, schema_editor):
    """Kelompok.member held operator ids as "38,49,35"; keep them, in that order, as KelompokMember rows."""
    Kelompok = apps.get_model('core', 'Kelompok')
    KelompokMember = apps.get_model('core', 'KelompokMember')
    Operator = apps.get_model('core', 'Operator')
    operator_ids = set(Operator.objects.values_list('pk', flat=True))

    for kelompok in Kelompok.objects.all():
        ids = [int(pk) for pk in kelompok.member.split(',') if pk.strip().isdigit()]
        KelompokMember.objects.bulk_create(
            KelompokMember(kelompok=kelompok, operator_id=pk)
            for pk in dict.fromkeys(ids) if pk in operator_ids
        )


def copy_members_to_text(apps, schema_editor):
    Kelompok = apps.get_model('core', 'Kelompok')
    for kelompok in Kelompok.objects.all():
        kelompok.member = ','.join(str(pk) for pk in kelompok.memberships.order_by('id').values_list('operator_id', flat=True))
        kelompok.save(update_fields=['member'])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='operator',
            options={'ordering': ['name'], 'verbose_name': 'Petugas', 'verbose_name_plural': 'Petugas'},
        ),
        migrations.AlterField(
            model_name='kelompok',
            name='name',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6)], default=1, unique=True),
        ),
        migrations.CreateModel(
            name='KelompokMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kelompok', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='core.kelompok')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='core.operator')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='kelompok',
            name='members',
            field=models.ManyToManyField(blank=True, through='core.KelompokMember', to='core.operator'),
        ),
        migrations.AddConstraint(
            model_name='kelompokmember',
            constraint=models.UniqueConstraint(fields=('kelompok', 'operator'), name='unique_kelompok_member'),
        ),
        migrations.RunPython(copy_members_to_table, copy_members_to_text),
        migrations.RemoveField(
            model_name='kelompok',
            name='member',
        ),
    ]
