# Generated by Django 5.1.3 on 2026-09-11 02:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StationListModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network', models.CharField(max_length=5)),
                ('code', models.CharField(max_length=10)),
                ('province', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=200)),
                ('digitizer_type', models.CharField(max_length=100)),
                ('UPT', models.CharField(max_length=50)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CsRecordModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('cs_id', models.CharField(default='0', max_length=16, unique=True)),
                ('shift', models.CharField(choices=[('Pagi', 'Pagi'), ('Siang', 'Siang'), ('Malam', 'Malam'), ('Dini Hari', 'Dini Hari')], default='Pagi', max_length=15)),
                ('jam_pelaksanaan', models.CharField(choices=[('00:00 WIB', '00:00 WIB'), ('06:00 WIB', '06:00 WIB'), ('12:00 WIB', '12:00 WIB'), ('18:00 WIB', '18:00 WIB')], default='12:00 WIB', max_length=20)),
                ('kelompok', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6)], default=1)),
                ('gaps', models.TextField(blank=True, max_length=10000, null=True)),
                ('spikes', models.TextField(blank=True, max_length=10000, null=True)),
                ('blanks', models.TextField(blank=True, max_length=10000, null=True)),
                ('slmon', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('count_gaps', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('count_spikes', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('count_blanks', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('slmon_image', models.ImageField(blank=True, null=True, upload_to='cl_seiscomp/slmon_images/')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.operator')),
            ],
        ),
    ]
