# Generated by Django 5.1.3 on 2026-09-11 02:49

import core.choices
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_seiscomp', '0001_initial'),
        ('core', '0002_alter_operator_options_remove_kelompok_member_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csrecordmodel',
            name='date',
            field=models.DateField(default=core.choices.local_today),
        ),
        migrations.AlterField(
            model_name='csrecordmodel',
            name='kelompok',
            field=models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6)], db_index=True, default=1),
        ),
        migrations.AlterField(
            model_name='csrecordmodel',
            name='operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.operator'),
        ),
        migrations.AddIndex(
            model_name='csrecordmodel',
            index=models.Index(fields=['date', 'shift', 'kelompok'], name='cl_seiscomp_csrecordmodel_slot'),
        ),
    ]
