# Generated by Django 5.1.3 on 2026-09-11 02:45

import core.choices
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_stasiun', models.CharField(max_length=20, unique=True)),
                ('lokasi', models.CharField(blank=True, max_length=200, null=True)),
                ('deskripsi_error', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='QcRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=core.choices.local_today)),
                ('qc_id', models.CharField(default='0', max_length=16, unique=True)),
                ('shift', models.CharField(choices=[('Pagi', 'Pagi'), ('Siang', 'Siang'), ('Malam', 'Malam'), ('Dini Hari', 'Dini Hari')], default='Pagi', max_length=15)),
                ('kelompok', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='1', max_length=1)),
                ('jam_pelaksanaan', models.TimeField(default=core.choices.local_time_now)),
                ('qc_prev', models.TextField(default='0')),
                ('qc', models.TextField(default='0')),
                ('NIP', models.CharField(default='0', max_length=18)),
                ('event_indonesia', models.IntegerField(default=0)),
                ('event_luar', models.IntegerField(default=0)),
                ('kel_sebelum', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='1', max_length=1)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.operator')),
            ],
        ),
    ]
