# Generated by Django 5.1.3 on 2026-09-11 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SlmonSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_time', models.DateTimeField(unique=True)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('stations', models.JSONField(default=list)),
            ],
            options={
                'ordering': ['-data_time'],
            },
        ),
    ]
