# Generated by Django 5.1.3 on 2026-09-11 02:45

import bast.models
import core.choices
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BastRecordModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=core.choices.local_today)),
                ('bast_id', models.CharField(default='0', max_length=18, unique=True)),
                ('waktu_pelaksanaan', models.CharField(blank=True, choices=[('08:00 - 14:00 WIB', '08:00 - 14:00 WIB'), ('14:00 - 20:00 WIB', '14:00 - 20:00 WIB'), ('20:00 - 02:00 WIB', '20:00 - 02:00 WIB'), ('02:00 - 08:30 WIB', '02:00 - 08:30 WIB')], default='08:00 - 14:00 WIB', max_length=20, null=True)),
                ('shift', models.CharField(choices=[('Pagi', 'Pagi'), ('Siang', 'Siang'), ('Malam', 'Malam'), ('Dini Hari', 'Dini Hari')], default='Pagi', max_length=15)),
                ('kelompok', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='1', max_length=1)),
                ('kel_berikut', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='1', max_length=1)),
                ('events', models.TextField(default='0')),
                ('NIP', models.CharField(blank=True, default='0', max_length=18)),
                ('event_indonesia', models.IntegerField(default=0)),
                ('event_luar', models.IntegerField(default=0)),
                ('event_dirasakan', models.IntegerField(default=0)),
                ('event_dikirim', models.IntegerField(default=0)),
                ('member', models.TextField(default='', max_length=1000)),
                ('count_gaps', models.IntegerField(default=0)),
                ('count_spikes', models.IntegerField(default=0)),
                ('count_blanks', models.IntegerField(default=0)),
                ('waktu_cs', models.CharField(blank=True, choices=[('00:00 WIB', '00:00 WIB'), ('06:00 WIB', '06:00 WIB'), ('12:00 WIB', '12:00 WIB'), ('18:00 WIB', '18:00 WIB')], default='00:00 WIB', max_length=20, null=True)),
                ('pulsa_poco', models.IntegerField(default=0)),
                ('poco_exp', models.DateField(default=bast.models.get_default_poco_exp)),
                ('samsung_exp', models.DateField(default=bast.models.get_default_samsung_exp)),
                ('notes', models.TextField(blank=True, default='', max_length=1000, null=True)),
                ('spv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.operator')),
            ],
        ),
    ]
