# Generated by Django 5.1.3 on 2026-09-11 09:03

import core.choices
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_alter_operator_options_remove_kelompok_member_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form', models.CharField(choices=[('email_web', 'Monitoring Email, Web, Medsos dan WRS-NG'), ('device', 'Checklist Sirine, SeisComP, TOAST, Diseminasi, TSP, WRS NG')], max_length=20)),
                ('key', models.SlugField(max_length=40, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('kind', models.CharField(choices=[('email', 'Email: akses Y/N, dijawab (J/BJ), forward ke'), ('web', 'Web: akses Y/N, dibaca (B/BB), disampaikan ke'), ('check', 'Checklist Ya/Tidak')], max_length=10)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('note', models.TextField(blank=True, help_text='Dicetak di bawah tabel, misalnya catatan penting.')),
            ],
            options={
                'ordering': ['form', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('name', models.CharField(max_length=300)),
                ('address', models.CharField(blank=True, help_text='Alamat web, username email atau alamat aplikasi.', max_length=300)),
                ('password', models.CharField(blank=True, help_text='Ikut dicetak di formulir.', max_length=200)),
                ('active', models.BooleanField(default=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='monitoring.checklistsection')),
            ],
            options={
                'ordering': ['section', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DeviceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=core.choices.local_today)),
                ('shift', models.CharField(choices=[('Pagi', 'Pagi'), ('Siang', 'Siang'), ('Malam', 'Malam'), ('Dini Hari', 'Dini Hari')], default='Pagi', max_length=15)),
                ('kelompok', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6)], db_index=True, default=1)),
                ('check_time', models.TimeField(default=core.choices.local_time_now)),
                ('dc_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.operator')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DeviceAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_key', models.SlugField(max_length=40)),
                ('section_title', models.CharField(max_length=200)),
                ('kind', models.CharField(choices=[('email', 'Email: akses Y/N, dijawab (J/BJ), forward ke'), ('web', 'Web: akses Y/N, dibaca (B/BB), disampaikan ke'), ('check', 'Checklist Ya/Tidak')], max_length=10)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('item_name', models.CharField(max_length=300)),
                ('item_address', models.CharField(blank=True, max_length=300)),
                ('ok', models.BooleanField(null=True)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='monitoring.checklistitem')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='monitoring.devicerecord')),
            ],
            options={
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EmailWebRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=core.choices.local_today)),
                ('shift', models.CharField(choices=[('Pagi', 'Pagi'), ('Siang', 'Siang'), ('Malam', 'Malam'), ('Dini Hari', 'Dini Hari')], default='Pagi', max_length=15)),
                ('kelompok', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6)], db_index=True, default=1)),
                ('check_time', models.TimeField(default=core.choices.local_time_now)),
                ('ew_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.operator')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EmailWebAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_key', models.SlugField(max_length=40)),
                ('section_title', models.CharField(max_length=200)),
                ('kind', models.CharField(choices=[('email', 'Email: akses Y/N, dijawab (J/BJ), forward ke'), ('web', 'Web: akses Y/N, dibaca (B/BB), disampaikan ke'), ('check', 'Checklist Ya/Tidak')], max_length=10)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('item_name', models.CharField(max_length=300)),
                ('item_address', models.CharField(blank=True, max_length=300)),
                ('access', models.CharField(blank=True, choices=[('Y', 'Y'), ('N', 'N')], max_length=1)),
                ('info', models.CharField(blank=True, max_length=500)),
                ('confirmed', models.CharField(blank=True, max_length=2)),
                ('forward_to', models.CharField(blank=True, max_length=300)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='monitoring.checklistitem')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='monitoring.emailwebrecord')),
            ],
            options={
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='devicerecord',
            index=models.Index(fields=['date', 'shift', 'kelompok'], name='monitoring_devicerecord_slot'),
        ),
        migrations.AddIndex(
            model_name='emailwebrecord',
            index=models.Index(fields=['date', 'shift', 'kelompok'], name='monitoring_emailwebrecord_slot'),
        ),
    ]
