# Generated by Django 5.1.3 on 2026-09-11 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0003_template_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklistsection',
            name='form',
            field=models.CharField(choices=[('email_web', 'Checklist Email, Web & Medsos'), ('device', 'Checklist TOAST & Diseminasi')], max_length=20),
        ),
    ]
