# Generated by Django 5.1.3 on 2026-09-11 04:11

import core.choices
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_alter_operator_options_remove_kelompok_member_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=core.choices.local_today)),
                ('shift', models.CharField(choices=[('Pagi', 'Pagi'), ('Siang', 'Siang'), ('Malam', 'Malam'), ('Dini Hari', 'Dini Hari')], default='Pagi', max_length=15)),
                ('kelompok', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6)], db_index=True, default=1)),
                ('report_id', models.CharField(editable=False, max_length=16, unique=True)),
                ('report_date', models.DateField(unique=True)),
                ('events', models.TextField(blank=True, default='')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.operator')),
                ('spv', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supervised_daily_reports', to='core.operator')),
            ],
            options={
                'abstract': False,
                'indexes': [models.Index(fields=['date', 'shift', 'kelompok'], name='daily_report_dailyreport_slot')],
            },
        ),
    ]
