# Generated by Django 5.1.3 on 2026-09-11 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_operator_options_remove_kelompok_member_and_more'),
        ('daily_report', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyreport',
            name='spv',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supervised_daily_reports', to='core.operator'),
        ),
    ]
