# Generated by Django 5.1.3 on 2026-09-11 12:56

import core.choices
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_alter_operator_options_remove_kelompok_member_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TideGaugeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=core.choices.local_today)),
                ('shift', models.CharField(choices=[('Pagi', 'Pagi'), ('Siang', 'Siang'), ('Malam', 'Malam'), ('Dini Hari', 'Dini Hari')], default='Pagi', max_length=15)),
                ('kelompok', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6)], db_index=True, default=1)),
                ('tg_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('check_time', models.TimeField(default=core.choices.local_time_now)),
                ('data_time', models.DateTimeField(blank=True, null=True)),
                ('web_accessible', models.BooleanField(default=True)),
                ('stations', models.JSONField(blank=True, default=list)),
                ('count_total', models.PositiveSmallIntegerField(default=0)),
                ('count_gaps', models.PositiveSmallIntegerField(default=0)),
                ('count_spike', models.PositiveSmallIntegerField(default=0)),
                ('count_blank', models.PositiveSmallIntegerField(default=0)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.operator')),
            ],
            options={
                'abstract': False,
                'indexes': [models.Index(fields=['date', 'shift', 'kelompok'], name='tide_gauge_record_slot')],
            },
        ),
    ]
